### ISSUE TITLE
Q. mat-, “to eat” ERROR:

### ISSUE THREAD

**Issue by Eruanno-Matt** [pfstrack/eldamo#10]
I've identified a little error with the verb conjugation:
_Matuvatye_ | future 1st-sg | “you [shall] eat” |
Should be:
_Matuvatye_ | future 2nd-sg-familiar | “you [shall] eat” |

Just to make this easier, I'll mark the pages linked to this error:
Q. mat- page: **_eldamo-0.5.6/content/words/word-342927741.html_**
Q. future tense page: **_eldamo-0.5.6/content/words/word-2817430301.html_**
Q. Quenya phrase: **_eldamo-0.5.6/content/words/word-1368676801.html_**

Hope this helps!

**Comment by pfstrack** [comment]
Thanks, I will fix this in the next version of the release.

**Comment by pfstrack** [comment]
Fixed: http://eldamo.org/content/words/word-342927741.html
