### ISSUE TITLE
(very minor) Typo at entry tew

### ISSUE THREAD

**Issue by BenTalagan** [pfstrack/eldamo#11]
Hi Paul!

The following sentence :

```
but is clearly glossed as singular “letter” wiwith primitive form <i>tekmē</i>
```

Should be corrected as :

``` 
but is clearly glossed as singular “letter” with primitive form <i>tekmē</i>
```

There's also a non breaking space before the 'wiwith' typo (U+A0) and i think there are a few others which can be found here and there into the xml source, generally (if not always) after an ending quote character (”) - I don't know if this is really intended or not.

**Comment by pfstrack** [comment]
Thanks, I will correct it in the next release. The non-breaking spaces are probably artifacts from copying data from spreadsheets, so I will clean those up too.

**Comment by pfstrack** [comment]
Fixed: http://eldamo.org/content/words/word-184661859.html

**Comment by BenTalagan** [comment]
Awesome. Thanks, Paul!

**Comment by pfstrack** [comment]
No problem. I appreciate the feedback.
