### ISSUE TITLE
Typo in Westron name for Rivendell

### ISSUE THREAD

**Issue by Tyelpion** [pfstrack/eldamo#2]
http://eldamo.org/content/words/word-1737448873.html

The right name should be *Karningul* as it was written in Appendix F. There is an *n* letter missed.

**Comment by pfstrack** [comment]
My apologies for not responding sooner. I didn't notice your comment until I was publishing release 0.5.1. Unfortunately that means it too late for me to fix is in that release. I will fix it in 0.5.2.

**Comment by pfstrack** [comment]
Fixed in 0.5.2 release:

http://eldamo.org/content/words/word-2779500767.html
