### ISSUE TITLE
About the Rohirric entries

### ISSUE THREAD

**Issue by Lucipetus** [pfstrack/eldamo#25]
I just noticed that Anglo-Saxon(-ish) words such as _Théoden_, _Holbytla_, etc. has been categorized as Rohirric.
Well, I know it's ok to say that in some context, just like in the body of the books, where English equals Westron. 
But the readers should know that the Anglo-Saxon names are but translations of the original Rohirric. _Holbytla(n)_ is AS translation of _kûd-dûkan_ - the actual original Rohirric name, not an obsolete Westron name as currently labeled (as _Wes. †_). The _Appendix F - II On Translation_ has it all explained.

Westron and Rohirric were contemporary languages that were related. When Tolkien translated (fictionally) the Red Book (supposedly mainly written in Westron) into English, he felt like to translate all the closely related languages such as Rohirric into something related to English. He chose Anglo-Saxon for Rohirric, and Gothic, I believe, for some of the ancient northern Mannish names.

So _kûd-dûkan_, _Lohtûr_ and the like should be Rohirric, while _Holbytla_, _Éothéod_ be put into a new category, say "Rohirric (in Anglo-Saxon representation)".

**Comment by pfstrack** [comment]
Strictly speaking, you are correct, but there are such a small number of genuine Rohirric words that it’s not worth the trouble of giving them their own language category. I lump them in as “archaic Westron” for now. That may change if/when new Westron and/or “true Rohirrim” information is published. There are similar issues with all the Mannish languages. Easterling (for example) is a grab bag of both ancient Easterling from the first age and later Easterling from the third age.
