### ISSUE TITLE
Umbarto, Oarel, Amon Gwareth, Amras entries

### ISSUE THREAD

**Issue by Ostesor** [pfstrack/eldamo#3]
http://eldamo.org/content/words/word-389468831.html

the name was given by Nerdanel not Indis :-)

http://eldamo.org/content/words/word-2470950471.html

Aurel comes from ✶awādelo as said
but Oarel comes from ✶atvadelo
WJ page 363: '3(c) Aurel < *aw(a)delo. Oärel < *atvadelo.'

In WJ page 200 t is seen that S. Amon Gwareth  was changed to Amon Gwared... They  are not variant forms... As I see it the suffic -eth was outdated and Gwared seems rather like an adjective giving it the meaning of Guarded Hill...

http://eldamo.org/content/words/word-2758841993.html

In Peoples of Middle Earth page 353 it is clearly seen that Amras was the last of the brothers to be born so it is clear that he was the seventh. So Amrod was Minyarussa and Amras was Atyarussa.

**Comment by pfstrack** [comment]
Thanks for the feedback. I will incorporate these fixes in the next release of the lexicon.

**Comment by pfstrack** [comment]
Fixed in v0.5.3
