### ISSUE TITLE
Minor Sindarin addition

### ISSUE THREAD

**Issue by Ostesor** [pfstrack/eldamo#30]
Add Tirith Aear. the Sea ward tower of Dol Amroth it is found in the Adventures of Tom Bombadil

**Comment by pfstrack** [comment]
Thanks. It will be in the next release.

**Comment by Ostesor** [comment]
Rog for the Woses is propably not Westron
Rog, pl. rogin is the word used by the Rohirrim for the druedain while wose  (M.Eenglish. wasa) is the translation of the word Rog.
See Last note of the Druedain chapter in the Unfinished Tales.

**Comment by pfstrack** [comment]
The Eldamo data model treats “True Rohirric” as an archaic dialect of Westron. Thus words like Rôg get dumped into the Westron language. Until we get more that a handful of words, it isn’t worth splitting out “True Rohirric” into its own language.

**Comment by pfstrack** [comment]
Fixed https://eldamo.org/content/words/word-530255251.html
