### ISSUE TITLE
Telperim should be marked with #, and rather Telperin

### ISSUE THREAD

**Issue by Pengolodh** [pfstrack/eldamo#36]
Since _Telperim_ is isolated from _Telperimpar_, a # marker should be present, if the notation scheme is to be followed.
And the form _Telperim-_ is most probably due to assimilation to following p. #_Telperin_ is much safer, Also cf. its cognate _celebren_ in Sindarin(N.) (which unlike Quenya, allows word final -m). And in fact #_-rin_ is already listed as a T. suffix.

**Comment by pfstrack** [comment]
You are right. I will fix it for the next release
