### ISSUE TITLE
HSD references

### ISSUE THREAD

**Issue by Omikhleia** [pfstrack/eldamo#39]
Greeetings M. Paul Strack, and congratulations for the excellent work done here.

A few minor small details regarding references to HSD follow below, as I used your own dictionary, in turn, to re-check a few points recently. Please feel free to take into account or not, at your own convenience ! 

Kind regards, 
Didier.

--

Réferences:
> Hiswelókë’s Sindarin Dictionary (HSD)
> Didier Willis; 1999-2008; http://www.jrrvf.com/hisweloke/sindar/online/sindar/dict-sd-en.htm
> The most extensive list of Sindarin words available on the internet. Unfortunately, it does not yet include all the Sindarin words from PE17 or later. (...)

You might possibly want to rephrase a bit, by new name, and refer to the github repository:
> A Sindarin and Noldorin dictionary (HSD, formerly Hiswelókë’s Sindarin Dictionary)
> The Sindarin Dictionary Project, 1999-2008, 2010-2011, 2014, 2019, https://github.com/Omikhleia/sindict
> (As of 2021, it probably does not yet include all the Sindarin words from PE17.)

I'm am pretty sure the last version there should include everything up to VT50 and PE22, except some entries from PE17 where the coverage status is unclear (it's likely partial, at best). The online version hosted on JRRVF should, I expect, be updated at one point sooner or later (so technically the link could also stay eventually, I assume), but anyhow the "latest" XML source, FWIW, is now on github.

Other points:
- Entry **dem** was fixed (but basically states what you said, with reference to Eldamo, so I think your text may likely stay unchanged.)
- Entry **ened** "In his Sindarin dictionary (HSD/ened), Didier Willis suggested _ened_ as the likely “final” form based on _Enedwaith_": I can't remember having personally authored that annotation (which is not unexpected, in a work that at one point tried to be collegial, FWIW). Could be rephrased in a more neutral way here: "In HSD/ened, it is suggested..."
- Entry **fuir**: "Didier Willis suggested fair, but this is likely incorrect, as suggested to me in a private chat by Elaran on 2018-08-26" — Not very clear to me what it refers to (though _fair_ is suggested as normalization for _feir_, but in a different entry, so perhaps unsound indeed. Anyhow I don't think it pertains to the _fuir_ entry).
- Entry **arnen**:  "Roman Rausch suggested ... This theory was also suggested by Didier Willis in his Sindarin dictionary (HSD/arnen), but I am not sure who first proposed this theory." — Personally, I don't really care who might have said it first or not, esp. for such an unimportant point of detail. Anyhow, for the record, my first mentioning of it was seemingly in (French) _Hiswelókë - Quatrième feuillet_, (2000, re-ed. august 2001), "Du détail géographique : Les Emyn Arnen" (pp. 119-124). The 2001 re-edition included an addendum on the (then) newly revealed meaning of Emyn Arnen and amended the earlier notes in accordance, leading to a formulation close to what the HSD eventually included. I have no remembrance of having discussed the topic with M. Rausch. Of course, he could as well have discovered the idea independently, earlier or later. And I wouldn't be surprised if the topic had been brought to Elfling at some point in 2000-2001, though I can't remember if it indeed did.
- Entry **dambeth**: "HSD incorrectly has _dambeth_" — Oops. This was fixed and annotated. Congrats for catching it.

**Comment by pfstrack** [comment]
Didier, it is marvelous to hear from you!

I was completely unaware of the Github site and further work on your dictionary's data model. I will of course update Eldamo to note its existence and (hopefully) eventual publication.

Your dictionary was one of the major inspirations of Eldamo, and my commentary on it were because I double-check Eldamo's Sindarin entries against HSD, and found numerous errors in the process.

I will certainly take your feedback and incorporate it in Eldamo for its next release.

**Comment by pfstrack** [comment]
You happened to post shortly before I was pushing a planned Eldamo release, so I've addressed your comments:

1) I updated the HSD description to point to the in-progress HSD work in github:

https://eldamo.org/content/references/ref-HSD.html

2) I update the _enedh_ entry to be more neutral, as requested:

https://eldamo.org/content/words/word-1623970613.html

3) I clarified the _fuir_ entry to give more context:

https://eldamo.org/content/words/word-780748133.html

The motivation for that note is research I did a couple years ago into the likely development of *phorya in Sindarin vs. Noldorin as discussed here:

https://eldamo.org/content/words/word-1787434575.html

4) I credited _arnen_ "royal" to you:

https://eldamo.org/content/words/word-2684605069.html

When I double-checked Roman Rausch's writing, he credited it to you as well:

http://www.sindanoorie.net/art/RS_TI_WR.html#LonnathErnin
