### ISSUE TITLE
lungu, parya

### ISSUE THREAD

**Issue by JPRidgeway** [pfstrack/eldamo#4]
http://eldamo.org/content/words/word-1877407.html - the absence of a macron over paranye is most definitely a slip, and even if a possibility of A-verb *para or sirya-type *parya is not out of the question, the aorist form pare is now well-attested in contemporary PE22:154, cuita'r pare.

http://eldamo.org/content/words/word-4278088233.html - if a separate word, should be *lungo (PE19:060 et al.). Though could be a compound-only form on the lines of PE21:80 (Ia) description, especially if we wish to retain Ety/LUG.

**Comment by pfstrack** [comment]
You are right on both counts. I will make these revisions on the next release: parya- >> par- and lungu >> lungo (lungu-).

**Comment by pfstrack** [comment]
Fixed in v0.5.3
