### ISSUE TITLE
Invalid XML

### ISSUE THREAD

**Issue by arnog** [pfstrack/eldamo#41]
At line 18824 (entry for "caras"), it looks like the `<combine>` tag does not have a matching closing tag. Not sure if there's some  info missing, or if the `<combine>` tag should just not be there, but as is the XML document is flagged as invalid.

Version 0.8.0

**Comment by pfstrack** [comment]
Oh weird, I’m not sure how that happen. I will try to put together a quick and dirty fix by this weekend.

**Comment by pfstrack** [comment]
Arnog, I'm pretty far along on Eldamo 8.1 and branching the code to fix this in github would actually be a bit of a pain. However, the XML file on the web site is both valid and correct, so I recommend you use that:

https://eldamo.org/

Download the file in the raw-data eldamo-data.xml link

**Comment by arnog** [comment]
No worries, I applied a local fix, but I can wait for 0.8.1 for an official fix. I just wanted to make sure this was on your radar.

**Comment by pfstrack** [comment]
Fixed a while ago.
