### ISSUE TITLE
[Bug] C<->K conversion is peformed not only for Eldarin, but for other Tolkien languages and for glosses

### ISSUE THREAD

**Issue by stepa2** [pfstrack/eldamo#42]
Examples search requests:
- [Language=Valarin] `word=c` -- includes words with `k`, no words with `c` found
- `gloss=kastle` -- finds words with gloss 'castle'
- `gloss=scill` -- finds words with gloss 'skill'

**Comment by pfstrack** [comment]
Fixed in 0.8.4, the c/k switch has been removed since it was causing to many problems
