### ISSUE TITLE
New bot in Mastobot based on Eldamo dictionaries

### ISSUE THREAD

**Issue by kergozh** [pfstrack/eldamo#46]
Regards, Paul. I would like to inform you that I have made a bot that allows to look up words from Tolkien's languages ​​from the Eldamo dictionaries. I have not found any other system to communicate with you, so I inform you from here :-). Thank you for your great work.

@lambebot@frikiverse.zone
https://frikiverse.zone/@lambebot

**Comment by pfstrack** [comment]
Thank you, it looks interesting. If you are interested in Tolkien’s languages, the Vinye Lambengolmor discord server is a good place to visit: https://discordapp.com/invite/Dhmyzrf

I’m reachable there.

**Comment by Shyk92** [comment]
To this effect; I was wondering if there had been any thought or effort either vectorizing Eldamo for LLM context or perhaps fine-tuning a model on this source. 

I have been writing new sindarin phrases for songs with LLMs  lately, (Bræg firais sí lû - Strength from darkness through) but I think a fine-tuned model implementing this knowledge base would be a welcome tool for all interested in the subject 

If not I can certainly take a whack at it
@pfstrack
