### ISSUE TITLE
Typo in reference for the sindarin word 'morchant'

### ISSUE THREAD

**Issue by BenTalagan** [pfstrack/eldamo#51]
The reference given for the word [morchant](https://eldamo.org/content/words/word-4068001285.html) in the description/comment is wrong (VT 49/9 , but it should be corrected to VT 42/9). The reference to the editorial footnote however is correct (VT 42/28 note 18).

**Comment by pfstrack** [comment]
Thank you. I've fixed this issue for the next release of Eldamo.
